### ISSUE TITLE
erro ao iniciar o arquivo [Start].bat

### ISSUE THREAD

**Issue by aquila0101** [eclipt69/neural-network-aimbot#1]
![Captura de tela 2022-12-12 194600](https://user-images.githubusercontent.com/84749877/207171516-edf9220f-717d-4cc3-a12e-6664d9bdef9a.png)

Estou usando o windows 10 e a versão do python é a 3.11

**Comment by eclipt69** [comment]
Tens que iniciar o rpograma a partir do [start].bat não a partir do loader.py, alem disso tens que ter as pastas no sitio correto (a pasta das libs e models deve estar na mesma que o start.bat) e para que o yolo3 funcione a 100% aconselho a usar python 3.8
Espero ter ajudado ;)

**Comment by aquila0101** [comment]
muito obrigado
